### ISSUE TITLE
Allow specifying optional tags for storage

### ISSUE THREAD

**Issue by ashevtsov-wawa** [codefresh-io/venona#472]
Our organization uses tags to track spending by department/project/etc.
Codefresh uses a lot of EBS volumes so we would like to get them tagged so their cost is reflected in the reports correctly.
Could you please add an option to specify custom/additional tags in `storage` block?
Example:
```yaml
storage:
  backend: ebs-csi
  fsType: ext4

  ebs:
    availabilityZone: us-east-1a
    volumeType: gp3
    encrypted: true
    tags:
      env: dev
      project: prj
```

Thank you!
